/* Generated by vite-plugin-env-parser */
/// <reference types="vite/client" />

declare module "vite-env" {
  readonly const VITE_PORT: number
  readonly const VITE_PUBLIC_PATH: string
  readonly const VITE_BASE_API: string
  readonly const VITE_DROP_CONSOLE: boolean
}
